services:
  mysqldb:
    image: mysql:8.0
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: school_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysqldb
  app:
    image: "ion21/online-school:latest"
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/school_db?autoReconnect=true&useSSL=false
    depends_on:
      - mysqldb


